name: lat_firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.0-146.2.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: 2.21.0
  firebase_auth: 4.12.0
  intl: ^0.17.0
  curved_navigation_bar: ^1.0.3
  cloud_firestore: ^4.12.1
  firebase_storage: 11.4.1
  nb_utils: ^4.6.22
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/image-login.png
    - images/profile-background.png
    - images/profile.png
    - images/book-list.png
    - images/upload-image.png
  uses-material-design: true
